// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // migrations precisam de conexão direta (sem pgbouncer); runtime usa DATABASE_URL via lib/db.ts
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
